stages:
  - test
  - build
  - deploy

variables:
    APP_VERSION: $CI_PIPELINE_IID



test-pipeline:
  stage: test
  script:
    - echo "Running tests..."


.build-backend:
  stage: build
  script:
    - cd backend
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker image ls
    - docker push --all-tags $CI_REGISTRY_IMAGE
    

    
  only:
    changes:
      - nestjs-backend/**

.deploy-backend:
  stage: deploy
  script:
    - cd backend
    - echo "Deploying backend..."
    - 
  only:
    changes:
      - nestjs-backend/**
