# Use the official Node.js 14 image as the base image
FROM node:22.3.0-alpine

# Set the working directory inside the container
# WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
# COPY package*.json ./

# Install the dependencies
# RUN npm install

# Copy the source code to the working directory
COPY . .

# Build the application
#RUN npm run build

# Expose the port that the application will listen on
#EXPOSE 8000

# Start the application
#CMD ["npm", "run", "start"]