name: Docker Image CICD

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]  

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin 

    - name: Build the Docker image
      run: pwd ; cd nestjs-backend ; docker build -t fyp-be . 
    
    - name: Tag Docker image
      run: docker tag fyp-be:latest $DOCKER_USERNAME/fyp:latest

    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/fyp:latest
